[package]
name = "dex-indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
burberry.workspace = true
ethers.workspace = true
eyre.workspace = true
serde.workspace = true
serde_json.workspace = true
